'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname,'../ShadowQuest/web/ios-bridge.js'),'utf8');
const sent = [];
const initial = {run:{status:'idle'},workouts:[],gifts:[]};
const win = {__shadowQuestInitialState: initial,webkit:{messageHandlers:{hunter:{postMessage: message => sent.push(message)}}}};
vm.runInNewContext(source, {window: win});
assert.equal(JSON.parse(win.Hunter.getState()).run.status,'idle');
assert(Object.isFrozen(win.Hunter));
assert.equal(Object.keys(win.Hunter).length,39);
win.Hunter.savePushups(12);
assert.equal(sent[0].method,'savePushups');
assert.equal(sent[0].args[0],12);
win.Hunter.setSquatPreviewBounds(JSON.stringify({x:2,y:3,width:240,height:300,visible:true}));
assert.equal(sent[1].method,'setSquatPreviewBounds');
assert.equal(JSON.parse(sent[1].args[0]).x,2);
let received;
win.onNativeState = state => {received = state;};
const updated = {run:{status:'running'},workouts:[{type:'pushups',reps:12,xp:24}],gifts:[]};
win.__shadowQuestReceiveState(updated);
assert.equal(received,updated);
assert.equal(JSON.parse(win.Hunter.getState()).workouts[0].xp,24);
win.__shadowQuestReceiveState({invalid:true});
assert.equal(received,updated);
// Browser previews must not impersonate an installed app.
const preview = {};
vm.runInNewContext(source,{window:preview});
assert.equal(preview.Hunter,undefined);
console.log('iOS Hunter bridge: protocol, native dispatch, cached state and browser fallback passed');
